# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

!pip install pandas --quiet

import pandas as pd

medical_df = pd.read_csv('hospital.csv', sep=',')

#Split the single column into multiple columns
medical_df = medical_df.iloc[:, 0].str.split(',', expand=True)

#Set proper column names
medical_df.columns = ['age', 'gender', 'bmi', 'children', 'smoker', 'region', 'charges']

#Convert numeric columns
medical_df['age'] = pd.to_numeric(medical_df['age'])
medical_df['bmi'] = pd.to_numeric(medical_df['bmi'])
medical_df['children'] = pd.to_numeric(medical_df['children'])
medical_df['charges'] = pd.to_numeric(medical_df['charges'])

#Check the result
medical_df.head()

medical_df.shape
medical_df.info()
medical_df['age'].describe()

print(medical_df.columns)
Index(['age', 'gender', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype = )

medical_df.describe()

!pip install plotly matplotlib seaborn --quiet

# Commented out IPython magic to ensure Python compatibility.
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

#matplot lib for graphs
#seaborn for better graphs and statistics
#plotly for interactivity

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

medical_df.age.describe()

fig = px.histogram(medical_df, x='age', marginal='box', nbins=47, title='Distribution of Age')
fig.update_layout(bargap=0.1)
fig.show()

#px is plotly express

fig = px.histogram(medical_df, x='bmi', marginal='box', color_discrete_sequence=['red'], title='Distribution of BMI(Body Mass Index)')
fig.update_layout(bargap=0.1)
fig.show()

#We are using histogram only instead of other graphs
#for frequency distribution analysis and to compare two values

fig = px.histogram(medical_df, x='charges', marginal='box', color='smoker', color_discrete_sequence=['green','grey'], title='Annual Medical Charges')
fig.update_layout(bargap=0.1)
fig.show()

medical_df.smoker.value_counts()

px.histogram(medical_df, x = 'smoker', color='gender', title="Smoker")

fig = px.scatter(medical_df, x='age', y='charges', color='smoker', opacity=0.8, hover_data=['gender'], title='Age vs Charges')
fig.update_traces(marker_size=5)
fig.show()

#opacity to create slightly transparent dots
#hover to show info about a point when hovered

fig = px.scatter(medical_df, x='bmi', y='charges', color='smoker', opacity=0.8, hover_data=['gender'], title='BMI vs Charges')
fig.update_traces(marker_size=5)
fig.show()

medical_df.charges.corr(medical_df.age)

medical_df.charges.corr(medical_df.bmi)

smoker_values = {'no': 0, 'yes': 1}
smoker_numeric = medical_df.smoker.map(smoker_values)
medical_df.charges.corr(smoker_numeric)

gender_values = {'male': 0, 'female': 1}
gender_numeric = medical_df.gender.map(gender_values)
medical_df.charges.corr(gender_numeric)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

#Fits the categories and converts them to integers(eg, 0 and 1)

medical_df['gender'] = le.fit_transform(medical_df['gender'])

medical_df['smoker'] = le.fit_transform(medical_df['smoker'])

medical_df['region'] = le.fit_transform(medical_df['region'])

medical_df.head()

px.scatter(medical_df, x='age', y='age')

medical_df.corr()

sns.heatmap(medical_df.corr(), cmap='Reds', annot=True)
plt.title('Correlation Matrix')